# Release Schedule Configuration
# This file defines the automated release schedule for the dotfiles project

schedules:
  # Production releases
  production:
    # Monthly minor releases (first Monday of each month)
    minor:
      schedule: "0 9 1-7 * 1"  # First Monday at 9 AM UTC
      description: "Monthly feature release with new functionality"
      
    # Weekly patch releases (every Monday)
    patch:
      schedule: "0 9 * * 1"     # Every Monday at 9 AM UTC
      description: "Weekly bug fixes and minor improvements"
      auto_merge_prs: true      # Automatically merge approved bug fix PRs

  # Pre-release channels
  prerelease:
    # Daily alpha builds (weekdays only)
    alpha:
      schedule: "0 2 * * 1-5"   # 2 AM UTC, Monday-Friday
      description: "Daily alpha builds with latest changes"
      branches: ["main", "develop"]
      
    # Weekly beta releases (Fridays)
    beta:
      schedule: "0 14 * * 5"    # 2 PM UTC on Fridays
      description: "Weekly beta releases for testing"
      min_commits: 5            # Only release if 5+ commits since last beta
      
    # Release candidates (manual trigger)
    rc:
      manual_only: true
      description: "Release candidates before major/minor releases"

# Version bumping rules
version_rules:
  # Commit message patterns that trigger version bumps
  major:
    patterns:
      - "BREAKING CHANGE:"
      - "^feat!:"
      - "^fix!:"
    require_approval: true      # Require manual approval for major releases
    
  minor:
    patterns:
      - "^feat:"
      - "^feat(.*!):"
    
  patch:
    patterns:
      - "^fix:"
      - "^perf:"
      - "^refactor:"
      - "^style:"
      - "^docs:"
      - "^test:"
      - "^chore:"

# Release channels
channels:
  stable:
    name: "Stable"
    description: "Production-ready releases"
    include_prereleases: false
    
  beta:
    name: "Beta"
    description: "Beta testing channel"
    include_prereleases: ["beta", "rc"]
    
  nightly:
    name: "Nightly"
    description: "Latest development builds"
    include_prereleases: ["alpha", "beta", "rc"]
    branch: "main"

# Changelog generation
changelog:
  sections:
    - title: "🚀 Features"
      labels: ["feature", "enhancement"]
      
    - title: "🐛 Bug Fixes"
      labels: ["bug", "fix"]
      
    - title: "📚 Documentation"
      labels: ["documentation", "docs"]
      
    - title: "🔧 Maintenance"
      labels: ["chore", "maintenance"]
      
    - title: "⚡ Performance"
      labels: ["performance"]
      
    - title: "🔒 Security"
      labels: ["security"]

# Auto-labeling rules for PRs
auto_labels:
  - pattern: "^feat"
    labels: ["feature"]
    
  - pattern: "^fix"
    labels: ["bug"]
    
  - pattern: "^docs"
    labels: ["documentation"]
    
  - pattern: "^chore"
    labels: ["chore"]
    
  - pattern: "BREAKING CHANGE"
    labels: ["breaking-change", "major"]