repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.20.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]

-   repo: local
    hooks:
    -   id: changelog
        name: Check Changelog
        entry: bash -c 'if git diff --cached --name-only | grep -q "^CHANGELOG.md$"; then echo "Changelog modified, please ensure it follows the format"; exit 1; fi'
        language: system
        types: [file]
        files: ^CHANGELOG\.md$
        pass_filenames: false
