version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/home/vscode/.gitconfig
      - ~/.ssh:/home/vscode/.ssh
      - ~/.aws:/home/vscode/.aws
      - ~/.azure:/home/vscode/.azure
      - ~/.config/gcloud:/home/vscode/.config/gcloud
    command: sleep infinity
    environment:
      - DOCKER_BUILDKIT=1
      - COMPOSE_DOCKER_CLI_BUILD=1
    ports:
      - "3000:3000"  # Web app
      - "8000:8000"  # API
      - "8888:8888"  # Jupyter
      - "6060:6060"  # Go docs
      - "8001:8001"  # Rust docs
    networks:
      - dev

  db:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    ports:
      - "5432:5432"
    networks:
      - dev

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - dev

  minio:
    image: minio/minio
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  minio-data: 